### PR TITLE
Implementing vale

### LINKED ISSUE #337: Implementing ``vale``
Implementing Vale as a documentation linter: the documentation team has asked the PyAnsys libraries to implement `vale` (a documentation linter) to ease their review process. This linter detects easy mistakes and informs developers where they should modify their docstrings.

### PR DESCRIPTION
**Pull request by RobPasMue**
Closes #337

### CODE REVIEW

**Comment by RobPasMue** [comment]
``Vale`` is in place @PipKat - you can go through the review whenever you can. Thanks in advance!

**Comment by PipKat** [comment]
@RobPasMue I have to quit for the day. There are a handful of Vale issues that I will fix in the morning. However, most of them are in the autosummary directory. Would you mind telling me how to get rid of them? Are there files committed that shouldn't be--or do we have to mark folders/files so that Vale doesn't check them?

**Comment by RobPasMue** [comment]
> @RobPasMue I have to quit for the day. There are a handful of Vale issues that I will fix in the morning. However, most of them are in the autosummary directory. Would you mind telling me how to get rid of them? Are there files committed that shouldn't be--or do we have to mark folders/files so that Vale doesn't check them?

Interesting, let me look into it! The ``_autosummary`` folder shouldn't exist, since it is autogenerated when building the docs...

**Comment by RobPasMue** [comment]
Aaah, I see what the problem was. The templates were being evaluated by vale, and they shouldn't be. I just set some ``vale`` related statements to ignore the files from the linter process. It should work now =)

**Comment by ninad-kamat** [comment]
@waltersma Can you please review the changes to documentation that are done in this PR?

**Review by waltersma — APPROVED** [review]

**Comment by RobPasMue** [comment]
Feel free to merge when desired @ninad-kamat @waltersma

**Review by ninad-kamat — APPROVED** [review]

**Pull request merged**
