### PR TITLE
Workflow using pyansys actions

### LINKED ISSUE #339: Implementing PyAnsys actions in workflow
Moving workflow to use PyAnsys actions: we are trying to standardize the workflows as well and making reusable actions for all projects. The majority of your workflow could be handled using these actions.

### PR DESCRIPTION
**Pull request by RobPasMue**
Closes #339

### CODE REVIEW

**Comment by RobPasMue** [comment]
Hi @ninad-kamat - got the workflow working. This will publish dev docs to the ``gh-pages`` branch and will start the transition to the multidocs as well. Still needs some fine tuning probably regarding coverage flags but overall the repo behaved well to the actions =) Let me know what you think, doubts etc.

**Comment by RobPasMue** [comment]
Presenting workflow graph:
image

See also https://github.com/pyansys/pyprimemesh/actions/runs/4086124385

**Comment by RobPasMue** [comment]
Hi @ninad-kamat, warnings are raised when building the docs. Eventually these should be solved. But in the meantime I am just going to ignore them since they are not blocking/critical and they already existed. Feel free to merge this PR if you are fine with it. I'm OoO on Monday. I'll get back to the multi-version documentation on Tuesday (it will be ready before 0.3.0 release, you can count on it).

**Comment by ninad-kamat** [comment]
@RobPasMue Looks good to me.

**Review by ninad-kamat — APPROVED** [review]

**Pull request merged**
